/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Game = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'genre' : IDL.Text,
  'rating' : IDL.Nat8,
  'releaseYear' : IDL.Nat16,
  'developer' : IDL.Text,
});

export const idlService = IDL.Service({
  'filterByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
  'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getPickOfTheDay' : IDL.Func([], [Game], ['query']),
  'searchByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Game = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'genre' : IDL.Text,
    'rating' : IDL.Nat8,
    'releaseYear' : IDL.Nat16,
    'developer' : IDL.Text,
  });
  
  return IDL.Service({
    'filterByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
    'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getPickOfTheDay' : IDL.Func([], [Game], ['query']),
    'searchByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };